name: Build and Release Arch Linux Package

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

# Add permissions needed for creating releases
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Update package database
        run: pacman -Syu --noconfirm

      - name: Install build dependencies
        run: pacman -S --noconfirm git python python-pip python-uv base-devel sudo

      - name: Create build user
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Install yay
        run: |
          cd /tmp
          sudo -u builder git clone https://aur.archlinux.org/yay.git
          cd yay
          sudo -u builder makepkg -si --noconfirm

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup directories
        run: |
          mkdir -p /home/builder/build
          cp -r ./* /home/builder/build/
          chown -R builder:builder /home/builder/build

      - name: Extract version from PKGBUILD
        id: get_version
        run: |
          VERSION=$(grep -Po "(?<=pkgver=)([0-9]+\.[0-9]+\.[0-9]+)" PKGBUILD)
          echo "PACKAGE_VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "Extracted version: ${VERSION}"

      - name: Build package
        run: |
          cd /home/builder/build
          sudo -u builder bash -c "
            # Install dependencies from official repos first
            yay -S --noconfirm --needed ntfs-3g dosfstools rsync polkit libcdio
            # Install AUR dependencies
            yay -S --noconfirm --needed ms-sys
            # Build the package
            makepkg -s --noconfirm
          "

      - name: List built packages
        run: |
          ls -la /home/builder/build/*.pkg.tar.zst

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: /home/builder/build/justdd-${{ steps.get_version.outputs.PACKAGE_VERSION }}-*.pkg.tar.zst
          draft: false
          prerelease: false
