name: Build Packages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [debian:bookworm, fedora:latest]
    container: ${{ matrix.container }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install base system deps
        run: |
          if command -v apt-get >/dev/null; then
            apt-get update
            apt-get install -y build-essential debhelper devscripts python3 curl rpm git make wget file patchelf rpmdevtools
          elif command -v dnf >/dev/null; then
            dnf -y install git python3 python3-devel rpm-build rpmdevtools curl make wget file patchelf
          fi

      - name: Install uv
        run: |
          # Try pip first as it's more reliable in CI environments
          if pip3 install uv --break-system-packages 2>/dev/null; then
            echo "uv installed via pip3"
          else
            curl -LsSf https://astral.sh/uv/install.sh | sh
          fi
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Sync deps (all extras)
        run: uv sync --all-extras

      - name: Build all packages
        run: bash packaging/build-scripts/build-all.sh

      - name: List artifacts
        run: ls -la dist || true

      - name: Release (tag only)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.deb
            dist/*.rpm
            dist/*.pkg.tar.zst