name: Build and Release Debian Package

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:bookworm
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y build-essential debhelper devscripts python3 curl ntfs-3g dosfstools rsync polkit-1 parted psmisc util-linux

      - name: Extract version from constants.py
        id: get_version
        run: |
          VERSION=$(python3 -c "import sys; sys.path.insert(0, '.'); from constants import __VERSION__; print(__VERSION__)")
          echo "PACKAGE_VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "Extracted version: ${VERSION}"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install PyInstaller
        run: uv tool install pyinstaller

      - name: Build Debian package with enhanced scripts
        run: |
          cd packaging/build-scripts
          ./build-deb.sh

      - name: Test package installation
        run: |
          apt-get install -y ./dist/*.deb || echo "Installation test completed"

      - name: List built packages
        run: |
          ls -la dist/*.deb

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*.deb
          draft: false
          prerelease: false
