name: Build and Release Fedora Package

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

# Add permissions needed for creating releases
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    container:
      image: fedora:latest
      options: ${{ matrix.arch == 'aarch64' && '--platform linux/arm64' || '--platform linux/amd64' }}

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Update system
        run: dnf -y update

      - name: Install dependencies
        run: |
          dnf -y install git python3 python3-pip rpm-build rpmdevtools python3-devel ntfs-3g-devel dosfstools rsync polkit

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from PKGBUILD
        id: get_version
        run: |
          VERSION=$(grep -Po "(?<=pkgver=)([0-9]+\.[0-9]+\.[0-9]+)" PKGBUILD)
          echo "PACKAGE_VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "Extracted version: ${VERSION}"

      - name: Setup RPM build environment
        run: |
          mkdir -p ~/rpmbuild/{SPECS,SOURCES,BUILD,RPMS,SRPMS}

      - name: Install uv and Python dependencies
        run: |
          pip install uv
          uv venv
          source ./.venv/bin/activate
          uv sync --all-extras
          pip install pyinstaller

      - name: Create spec file
        run: |
          cat > ~/rpmbuild/SPECS/justdd.spec << EOF
          Name:           justdd
          Version:        ${{ steps.get_version.outputs.PACKAGE_VERSION }}
          Release:        1%{?dist}
          Summary:        Simple graphical USB image writer for Linux and Windows ISOs

          License:        GPLv3
          URL:            https://github.com/xxanqw/justdd
          BuildArch:      ${{ matrix.arch }}

          Requires:       ntfs-3g, dosfstools, rsync, polkit

          %description
          JustDD is a simple, open-source graphical tool to write Linux and Windows ISO images to USB drives.
          It is designed for ease of use, safety, and flexibility, supporting both direct ISO writing (via dd)
          and advanced Windows USB preparation.

          %prep
          # No source unpacking needed as we're building directly from the workspace

          %build
          # Build will be handled in our GitHub Actions workflow

          %install
          mkdir -p %{buildroot}/usr/bin
          mkdir -p %{buildroot}/usr/share/pixmaps
          mkdir -p %{buildroot}/usr/share/applications

          install -m 755 %{_sourcedir}/justdd %{buildroot}/usr/bin/justdd
          install -m 644 %{_sourcedir}/justdd.png %{buildroot}/usr/share/pixmaps/justdd.png

          cat > %{buildroot}/usr/share/applications/justdd.desktop << EOT
          [Desktop Entry]
          Name=JustDD
          Comment=USB Image Writer for Linux and Windows ISOs
          Exec=justdd
          Icon=justdd
          Terminal=false
          Type=Application
          Categories=Utility;System;
          EOT

          %files
          /usr/bin/justdd
          /usr/share/pixmaps/justdd.png
          /usr/share/applications/justdd.desktop

          %post
          echo "----------------------------------------------------------------------"
          echo "NOTE: JustDD uses polkit for privilege escalation."
          echo "If polkit is not enabled by default in your distribution, you may"
          echo "need to start and enable the polkit service."
          echo "----------------------------------------------------------------------"

          %changelog
          * $(date '+%a %b %d %Y') GitHub Actions <actions@github.com> - ${{ steps.get_version.outputs.PACKAGE_VERSION }}-1
          - Automated build from GitHub release for ${{ matrix.arch }}
          EOF

      - name: Build binary
        run: |
          source ./.venv/bin/activate
          pyinstaller --onefile --add-data "images/icon.png:images" --name justdd app.py
          chmod +x dist/justdd
          cp dist/justdd ~/rpmbuild/SOURCES/
          cp images/icon.png ~/rpmbuild/SOURCES/justdd.png

      - name: Build RPM package
        run: |
          rpmbuild -ba ~/rpmbuild/SPECS/justdd.spec
          # Create a directory for artifacts
          mkdir -p ./release-artifacts
          # Copy the built RPM to the artifacts directory with a clear, arch-specific name
          cp ~/rpmbuild/RPMS/${{ matrix.arch }}/justdd-${{ steps.get_version.outputs.PACKAGE_VERSION }}*.rpm ./release-artifacts/justdd-${{ steps.get_version.outputs.PACKAGE_VERSION }}-${{ matrix.arch }}.rpm

      - name: List built packages
        run: |
          ls -la ./release-artifacts/*.rpm

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./release-artifacts/justdd-${{ steps.get_version.outputs.PACKAGE_VERSION }}-${{ matrix.arch }}.rpm
          draft: false
          prerelease: false
