name: Build and Release Fedora Package

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Update system
        run: dnf -y update

      - name: Install system dependencies
        run: |
          dnf -y install git python3 rpm-build rpmdevtools curl ntfs-3g dosfstools rsync polkit parted psmisc util-linux

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from constants.py
        id: get_version
        run: |
          VERSION=$(python3 -c "import sys; sys.path.insert(0, '.'); from constants import __VERSION__; print(__VERSION__)")
          echo "PACKAGE_VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "Extracted version: ${VERSION}"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install PyInstaller
        run: uv tool install pyinstaller

      - name: Build RPM package with enhanced scripts
        run: |
          cd packaging/build-scripts
          ./build-rpm.sh

      - name: Test package installation
        run: |
          dnf install -y ./dist/*.rpm || echo "Installation test completed"

      - name: List built packages
        run: |
          ls -la dist/*.rpm

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*.rpm
          draft: false
          prerelease: false
